// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQtwCcpScohH1ZGyHDbghvFd2zf2YzwY',
    appId: '1:1061045299900:web:e60982b5df535902fd3eb9',
    messagingSenderId: '1061045299900',
    projectId: 'crud-3d4f8',
    authDomain: 'crud-3d4f8.firebaseapp.com',
    storageBucket: 'crud-3d4f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNi26WgdIvI5g-SD9BtEmiiKEE4YVnbpU',
    appId: '1:1061045299900:android:3f147e446f174184fd3eb9',
    messagingSenderId: '1061045299900',
    projectId: 'crud-3d4f8',
    storageBucket: 'crud-3d4f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFqnkWkJOvvUClGSvObuWv5VD_9daj0Y',
    appId: '1:1061045299900:ios:f918d272ac3aaaedfd3eb9',
    messagingSenderId: '1061045299900',
    projectId: 'crud-3d4f8',
    storageBucket: 'crud-3d4f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
